cache:
  - C:\downloads\hunspell-1.3.3.tar.gz

environment:
  fast_finish: true
  matrix:
    - MSARCH: Win32
      VCVARS: vcvars32.bat
      PYTHON: "C:\\Python27"
    - MSARCH: x64
      VCVARS: amd64\vcvars64.bat
      PYTHON: "C:\\Python27-x64"
    - MSARCH: Win32
      VCVARS: vcvars32.bat
      PYTHON: "C:\\Python34"
    - MSARCH: x64
      VCVARS: amd64\vcvars64.bat
      PYTHON: "C:\\Python34-x64"
    - MSARCH: Win32
      VCVARS: vcvars32.bat
      PYTHON: "C:\\Python35"
    - MSARCH: x64
      VCVARS: amd64\vcvars64.bat
      PYTHON: "C:\\Python35-x64"
    - MSARCH: Win32
      VCVARS: vcvars32.bat
      PYTHON: "C:\\Python36"
    - MSARCH: x64
      VCVARS: amd64\vcvars64.bat
      PYTHON: "C:\\Python36-x64"
    - MSARCH: Win32
      VCVARS: vcvars32.bat
      PYTHON: "C:\\Python37"
    - MSARCH: x64
      VCVARS: amd64\vcvars64.bat
      PYTHON: "C:\\Python37-x64"
    - MSARCH: Win32
      VCVARS: vcvars32.bat
      PYTHON: "C:\\Python38"
    - MSARCH: x64
      VCVARS: amd64\vcvars64.bat
      PYTHON: "C:\\Python38-x64"

install:
  - "\"%VS140COMNTOOLS:~0,-14%VC\\bin\\\"%VCVARS%"
  - "echo \"%VS140COMNTOOLS:~0,-14%VC\\bin\\\"%VCVARS%"
  # Install wheel
  - "%PYTHON%\\python.exe -m pip install wheel"
  # get hunspell and prepare it for its compilation
  - cmd: >-
      C:

  - cd C:\
  - if not exist downloads mkdir downloads
  - cd downloads
  - echo %cd%
  - if not exist hunspell-1.3.3.tar.gz curl -L "https://sourceforge.net/projects/hunspell/files/Hunspell/1.3.3/hunspell-1.3.3.tar.gz" -O
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - if not exist dependenciesbuild mkdir dependenciesbuild
  - cmd: >-
      subst V: dependenciesbuild

  - cmd: >-
      V:

  - echo %cd%
  - 7z -y x C:\downloads\hunspell-1.3.3.tar.gz -so | 7z x -aoa -si -ttar
  - cd V:\hunspell-1.3.3\src\win_api
  - echo %cd%
  - copy "%APPVEYOR_BUILD_FOLDER%\\Hunspell.sln" .
  - copy %APPVEYOR_BUILD_FOLDER%\*.vcxproj .
  - devenv "Hunspell.sln" /upgrade
  - dir /s .
  - cmd: >-
      C:

  - cd "%APPVEYOR_BUILD_FOLDER%"
  - echo %cd%

image:
  - Visual Studio 2015
#  - Visual Studio 2017

before_build:
  - cmd: >-
      V:

  - cd V:\hunspell-1.3.3\src\win_api
  - echo %cd%
  - MSBuild "Hunspell.sln" -property:Configuration=Release -target:libhunspell -property:Platform=%MSARCH% -property:OutDir=V:\hunspell-1.3.3\src\win_api\x64\Release\libhunspell
  - cmd: >-
      C:

  - cd "%APPVEYOR_BUILD_FOLDER%"
  - echo %cd%

build_script:
  - "C:"
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - "%PYTHON%\\python.exe -m pip wheel hunspell"
  - dir /s .

artifacts:
  - path: "*.whl"
